name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    container:
      image: elementary/docker:unstable
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        apt update
        apt install -y valac meson appstream-util libgranite-dev libgtk-3-dev libxml2-dev libsqlite3-dev libnotify-dev libunity-dev libglib2.0-dev libsoup2.4-dev libwebkit2gtk-4.0-dev
    - name: Build
      run: |
        meson build
        ninja -C build
    - name: Test
      run: ninja -C build test
    - name: Install
      run: ninja -C build install
